version: '3.8'

services:
  flask:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0 --port=5000
